run:
    skip-dirs:
    - api
    - test
    - service

linters:
    presets:
    - bugs
    - unused
    - format
    - style

    disable:
    - unparam
    - gochecknoglobals
    - gochecknoinits
    - gocritic
    - lll
    - gosec
    - dupl
    - unparam
    - wrapcheck
    - gomnd
    - godox
    - testpackage
    - stylecheck
    - thelper
    - paralleltest
    - ifshort
    - goerr113
    - nlreturn
    - exhaustivestruct
    - errorlint
    - wsl
    - revive
    - exhaustive
    - promlinter
    - forbidigo
    - whitespace
    - nakedret
    - gofumpt
    - dogsled
    - nolintlint
    - forcetypeassert
    - makezero
    - godot
    - gci
    - wastedassign
    - interfacer
    - scopelint
    - golint
    - gomodguard
    - gomoddirectives
    - noctx
